import { DataTypes } from 'sequelize';
import {getSequelizeInstance} from '../config/database/SequelizeInstance.js';

const sequelize = getSequelizeInstance({database: 'foodpanda'});

const Orders = sequelize.define('Orders', {
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  token: DataTypes.STRING,
  code: DataTypes.STRING,
  cus_email: DataTypes.STRING,
  cus_first_name: DataTypes.STRING,
  cus_last_name: DataTypes.STRING,
  cus_phone: DataTypes.STRING,
  cus_flag: DataTypes.STRING,
  grand_total: DataTypes.FLOAT,
  pay_restaurant: DataTypes.FLOAT,
  rider_tip: DataTypes.FLOAT,
  vat_total: DataTypes.FLOAT,
  total_net: DataTypes.FLOAT,
  collect_from_customer: DataTypes.FLOAT,
  payment_type: DataTypes.STRING,
  payment_status: DataTypes.STRING,
  expedition_type: DataTypes.STRING,
  expected_delivery_time: DataTypes.DATE,
  express_delivery: DataTypes.BOOLEAN,
  rider_pickup_time: DataTypes.DATE,
  pickup_time: DataTypes.DATE,
  pickup_code: DataTypes.STRING,
  postcode: DataTypes.STRING,
  city: DataTypes.STRING,
  street: DataTypes.STRING,
  number: DataTypes.STRING,
  building: DataTypes.STRING,
  company: DataTypes.STRING,
  delivery_area: DataTypes.STRING,
  delivery_instructions: DataTypes.TEXT,
  delivery_main_area: DataTypes.STRING,
  entrance: DataTypes.STRING,
  flat_number: DataTypes.STRING,
  floor: DataTypes.STRING,
  intercom: DataTypes.STRING,
  latitude: DataTypes.DECIMAL(10, 8),
  longitude: DataTypes.DECIMAL(11, 8),
  comments: DataTypes.TEXT,
  country_code: DataTypes.STRING,
  currency_symbol: DataTypes.STRING,
  platform: DataTypes.STRING,
  platform_key: DataTypes.STRING,
  invoice_carrier_type: DataTypes.STRING,
  invoice_carrier_value: DataTypes.STRING,
  corporate_tax: DataTypes.FLOAT,
  test: DataTypes.BOOLEAN,
  short_code: DataTypes.STRING,
  platform_restaurant_id: DataTypes.STRING,
  expire_at: DataTypes.DATE,
  raw_payload: DataTypes.JSON,
  accepted_url: DataTypes.STRING,
  rejected_url: DataTypes.STRING,
  picked_up: DataTypes.BOOLEAN,
  prepared_url: DataTypes.STRING,
}, {
  tableName: 'orders',
  timestamps: true,
  underscored: true,
  paranoid: true,
});

export default Orders;
